<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\DataManager\DataContract\DataContract.csproj" />
      <ProjectReference Include="..\..\DomainModel\Models\Models.csproj" />
      <ProjectReference Include="..\..\Security\Authentication\Authentication.csproj" />
    </ItemGroup>

</Project>
