<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DataManager\DataContract\DataContract.csproj" />
      <ProjectReference Include="..\DomainModel\Models\Models.csproj" />
      <ProjectReference Include="..\Security\Authentication\Authentication.csproj" />
    </ItemGroup>

</Project>
